apiVersion: v1
kind: ServiceAccount
metadata:
  name: slack-holmes-bot-sa
  namespace: slack-holmes-bot
  annotations:
    # TODO: Replace this with your workload identity client ID (output from Terraform)
    azure.workload.identity/client-id: "YOUR_WORKLOAD_IDENTITY_CLIENT_ID"
    # TODO: Replace this with your Azure tenant ID
    azure.workload.identity/tenant-id: "YOUR_AZURE_TENANT_ID"
  labels:
    azure.workload.identity/use: "true"
