apiVersion: v1
kind: ServiceAccount
metadata:
  name: holmesgpt-holmes-service-account
  namespace: holmesgpt
  annotations:
    azure.workload.identity/client-id: "YOUR_WORKLOAD_IDENTITY_CLIENT_ID" # TODO: Replace this with your workload identity client ID (output from Terraform)
  labels:
    azure.workload.identity/use: "true"
